
model_name: model_tuh
save_path: null

epochs: 100

Dataset:
  shuffle: true
  x_basepath: data/TUH_TUSZ/TUH_dataset_PROCESSED/original
  y_basepath: data/TUH_TUSZ/TUH_dataset_PROCESSED/ICA
  x_fpath: Data_S{}.set
  y_fpath: Data_S{}_ICA.set
  sfreq: 128.0
  n_chan: null
  subjects_train:
    - ["002"]
    - ["003"]
    - ["004"]
    - ["005"]
    - ["006"]
    - ["007"]
    - ["008"]
    - ["009"]
    - ["010"]
    - ["011"]
    - ["012"]
    - ["013"]
    - ["014"]
  subjects_val:
    - ["015"]
    - ["016"]
    - ["017"]
    - ["018"]
    - ["019"]
    - ["020"]
  ch_names: null
  tmin: 200
  tmax: 800
  window_size: 4
  stride: 2

  