config:
  alpha: 0.4
  batch_size: 128
  bert_config_decoder: ./config_decoder_clamp.json
  embed_dim: 256
  mlm_probability: 0.15
  momentum: 0.995
  optimizer:
    lr: 5.0e-05
    opt: adamW
    weight_decay: 0.02
  property_width: 768
  schedular:
    cooldown_epochs: 0
    decay_rate: 1
    epochs: 5
    lr: 5.0e-05
    min_lr: 1.0e-05
    sched: cosine
    warmup_epochs: 20
    warmup_lr: 5.0e-05
  temp: 0.07
embed_dim: 768
pad_idx: 373
use_linear: false
vocab: !!python/object:decoder.vocab.Vocabulary
  end_idx: 375
  end_token: <eos>
  idx_to_token:
    0: '#'
    1: '%10'
    2: '%11'
    3: '%12'
    4: '%13'
    5: '%14'
    6: '%15'
    7: '%16'
    8: '%17'
    9: '%18'
    10: '%19'
    11: '%20'
    12: '%21'
    13: '%22'
    14: (
    15: )
    16: '*'
    17: '-'
    18: '1'
    19: '2'
    20: '3'
    21: '4'
    22: '5'
    23: '6'
    24: '7'
    25: '8'
    26: '9'
    27: '='
    28: B
    29: Br
    30: C
    31: Cl
    32: F
    33: I
    34: N
    35: O
    36: P
    37: S
    38: '[Ac]'
    39: '[Ag]'
    40: '[Al+2]'
    41: '[Al+]'
    42: '[Al-3]'
    43: '[Al-]'
    44: '[AlH+]'
    45: '[AlH-]'
    46: '[AlH2-]'
    47: '[AlH2]'
    48: '[AlH3-]'
    49: '[AlH]'
    50: '[Al]'
    51: '[Am]'
    52: '[Ar]'
    53: '[As+5]'
    54: '[As+]'
    55: '[As-]'
    56: '[AsH+]'
    57: '[AsH2+]'
    58: '[AsH2]'
    59: '[AsH3+]'
    60: '[AsH]'
    61: '[As]'
    62: '[At]'
    63: '[Au]'
    64: '[B-]'
    65: '[BH-]'
    66: '[BH2-]'
    67: '[BH2]'
    68: '[BH3-]'
    69: '[BH]'
    70: '[B]'
    71: '[Ba]'
    72: '[Be]'
    73: '[Bi+2]'
    74: '[Bi+]'
    75: '[Bi-]'
    76: '[BiH2]'
    77: '[BiH]'
    78: '[Bi]'
    79: '[Br+2]'
    80: '[Br+3]'
    81: '[Br+]'
    82: '[Br-]'
    83: '[Br]'
    84: '[C+]'
    85: '[C-]'
    86: '[CH+]'
    87: '[CH-]'
    88: '[CH2+]'
    89: '[CH2-]'
    90: '[CH2]'
    91: '[CH3+]'
    92: '[CH]'
    93: '[C]'
    94: '[Ca]'
    95: '[Cd-2]'
    96: '[Cd]'
    97: '[Ce+3]'
    98: '[Ce]'
    99: '[Cf]'
    100: '[Cl+2]'
    101: '[Cl+3]'
    102: '[Cl+]'
    103: '[ClH+2]'
    104: '[ClH+]'
    105: '[ClH2+2]'
    106: '[ClH3+3]'
    107: '[Cm]'
    108: '[Co+2]'
    109: '[Co-2]'
    110: '[Co]'
    111: '[Cr+2]'
    112: '[Cr+6]'
    113: '[Cr+]'
    114: '[Cr-2]'
    115: '[Cr]'
    116: '[Cs+]'
    117: '[Cs]'
    118: '[Cu-]'
    119: '[Cu]'
    120: '[Dy]'
    121: '[Er]'
    122: '[Es]'
    123: '[Eu]'
    124: '[Fe+3]'
    125: '[Fe+5]'
    126: '[Fe+]'
    127: '[Fe-2]'
    128: '[Fe-4]'
    129: '[Fe]'
    130: '[Ga-]'
    131: '[GaH2]'
    132: '[GaH]'
    133: '[Ga]'
    134: '[Gd+3]'
    135: '[Gd]'
    136: '[GeH2]'
    137: '[GeH3]'
    138: '[GeH]'
    139: '[Ge]'
    140: '[HH]'
    141: '[H]'
    142: '[Hf+2]'
    143: '[Hf]'
    144: '[Hg+]'
    145: '[HgH]'
    146: '[Hg]'
    147: '[Ho]'
    148: '[I+2]'
    149: '[I+3]'
    150: '[I+]'
    151: '[I-]'
    152: '[IH+]'
    153: '[IH2+]'
    154: '[IH]'
    155: '[InH2]'
    156: '[InH]'
    157: '[In]'
    158: '[Ir+2]'
    159: '[IrH2]'
    160: '[IrH3]'
    161: '[Ir]'
    162: '[K]'
    163: '[Kr]'
    164: '[La]'
    165: '[Li]'
    166: '[Lu]'
    167: '[Md]'
    168: '[Mg+]'
    169: '[Mg]'
    170: '[Mn]'
    171: '[Mo+2]'
    172: '[Mo+]'
    173: '[Mo-2]'
    174: '[MoH2]'
    175: '[Mo]'
    176: '[N+]'
    177: '[N-]'
    178: '[NH+]'
    179: '[NH-]'
    180: '[NH2+]'
    181: '[NH3+]'
    182: '[NH]'
    183: '[N]'
    184: '[Na]'
    185: '[Nb-2]'
    186: '[Nb]'
    187: '[Nd]'
    188: '[Ni+2]'
    189: '[Ni+]'
    190: '[Ni-3]'
    191: '[Ni-]'
    192: '[NiH]'
    193: '[Ni]'
    194: '[Np]'
    195: '[O+]'
    196: '[O-]'
    197: '[OH+]'
    198: '[OH2+]'
    199: '[OH3+]'
    200: '[OH]'
    201: '[O]'
    202: '[Os+2]'
    203: '[Os+8]'
    204: '[Os-]'
    205: '[OsH]'
    206: '[Os]'
    207: '[P+]'
    208: '[P-2]'
    209: '[P-]'
    210: '[PH+]'
    211: '[PH-]'
    212: '[PH2+]'
    213: '[PH2]'
    214: '[PH3+]'
    215: '[PH]'
    216: '[P]'
    217: '[PbH2]'
    218: '[PbH3]'
    219: '[PbH]'
    220: '[Pb]'
    221: '[Pd-]'
    222: '[Pd]'
    223: '[PoH2]'
    224: '[PoH]'
    225: '[Po]'
    226: '[Pr+]'
    227: '[Pr]'
    228: '[Pt-2]'
    229: '[PtH3]'
    230: '[Pt]'
    231: '[Pu]'
    232: '[Rb]'
    233: '[Re-2]'
    234: '[ReH2]'
    235: '[ReH4]'
    236: '[Re]'
    237: '[Rh+]'
    238: '[Rh-3]'
    239: '[Rh-]'
    240: '[RhH2]'
    241: '[Rh]'
    242: '[Rn]'
    243: '[Ru+]'
    244: '[Ru-4]'
    245: '[Ru]'
    246: '[S+]'
    247: '[S-]'
    248: '[SH+]'
    249: '[SH-]'
    250: '[SH2+]'
    251: '[SH2]'
    252: '[SH]'
    253: '[S]'
    254: '[Sb+]'
    255: '[Sb-]'
    256: '[SbH2]'
    257: '[SbH3+]'
    258: '[SbH3]'
    259: '[SbH]'
    260: '[Sb]'
    261: '[Sc]'
    262: '[Se+]'
    263: '[Se-]'
    264: '[SeH2+]'
    265: '[SeH2]'
    266: '[SeH]'
    267: '[Se]'
    268: '[Si+2]'
    269: '[Si+3]'
    270: '[Si+]'
    271: '[Si-]'
    272: '[SiH+2]'
    273: '[SiH+]'
    274: '[SiH-]'
    275: '[SiH2+]'
    276: '[SiH2-]'
    277: '[SiH2]'
    278: '[SiH3-]'
    279: '[SiH3]'
    280: '[SiH]'
    281: '[Si]'
    282: '[Sm]'
    283: '[Sn+2]'
    284: '[Sn+3]'
    285: '[Sn+]'
    286: '[Sn-]'
    287: '[SnH+]'
    288: '[SnH2-]'
    289: '[SnH2]'
    290: '[SnH3-]'
    291: '[SnH3]'
    292: '[SnH]'
    293: '[Sn]'
    294: '[Sr+2]'
    295: '[Sr]'
    296: '[Ta-2]'
    297: '[Ta-]'
    298: '[Ta]'
    299: '[Tb]'
    300: '[Tc+2]'
    301: '[Tc+3]'
    302: '[Tc+4]'
    303: '[Tc+5]'
    304: '[Tc]'
    305: '[Te+]'
    306: '[TeH3]'
    307: '[TeH4]'
    308: '[TeH]'
    309: '[Te]'
    310: '[Th+2]'
    311: '[Th]'
    312: '[Ti+2]'
    313: '[Ti+3]'
    314: '[Ti+]'
    315: '[Ti]'
    316: '[TlH2]'
    317: '[TlH]'
    318: '[Tl]'
    319: '[Tm]'
    320: '[U+2]'
    321: '[U+3]'
    322: '[UH2]'
    323: '[U]'
    324: '[V+2]'
    325: '[V+4]'
    326: '[V+]'
    327: '[V]'
    328: '[W+]'
    329: '[WH]'
    330: '[W]'
    331: '[XeH]'
    332: '[Xe]'
    333: '[YH]'
    334: '[Y]'
    335: '[Yb]'
    336: '[Zn+2]'
    337: '[Zn]'
    338: '[Zr+2]'
    339: '[Zr+]'
    340: '[Zr]'
    341: '[b-]'
    342: '[bH-]'
    343: '[c+]'
    344: '[c-]'
    345: '[cH+]'
    346: '[cH-]'
    347: '[c]'
    348: '[n+]'
    349: '[n-]'
    350: '[nH+]'
    351: '[nH]'
    352: '[o+]'
    353: '[oH+]'
    354: '[p+]'
    355: '[p-]'
    356: '[pH+]'
    357: '[pH]'
    358: '[s+]'
    359: '[sH+]'
    360: '[se+]'
    361: '[se]'
    362: '[si-]'
    363: '[siH]'
    364: '[si]'
    365: '[te+]'
    366: '[te]'
    367: b
    368: c
    369: n
    370: o
    371: p
    372: s
    373: <pad>
    374: <sos>
    375: <eos>
  pad_idx: 373
  pad_token: <pad>
  start_idx: 374
  start_token: <sos>
  token_to_idx:
    '#': 0
    '%10': 1
    '%11': 2
    '%12': 3
    '%13': 4
    '%14': 5
    '%15': 6
    '%16': 7
    '%17': 8
    '%18': 9
    '%19': 10
    '%20': 11
    '%21': 12
    '%22': 13
    (: 14
    ): 15
    '*': 16
    '-': 17
    '1': 18
    '2': 19
    '3': 20
    '4': 21
    '5': 22
    '6': 23
    '7': 24
    '8': 25
    '9': 26
    <eos>: 375
    <pad>: 373
    <sos>: 374
    '=': 27
    B: 28
    Br: 29
    C: 30
    Cl: 31
    F: 32
    I: 33
    N: 34
    O: 35
    P: 36
    S: 37
    '[Ac]': 38
    '[Ag]': 39
    '[Al+2]': 40
    '[Al+]': 41
    '[Al-3]': 42
    '[Al-]': 43
    '[AlH+]': 44
    '[AlH-]': 45
    '[AlH2-]': 46
    '[AlH2]': 47
    '[AlH3-]': 48
    '[AlH]': 49
    '[Al]': 50
    '[Am]': 51
    '[Ar]': 52
    '[As+5]': 53
    '[As+]': 54
    '[As-]': 55
    '[AsH+]': 56
    '[AsH2+]': 57
    '[AsH2]': 58
    '[AsH3+]': 59
    '[AsH]': 60
    '[As]': 61
    '[At]': 62
    '[Au]': 63
    '[B-]': 64
    '[BH-]': 65
    '[BH2-]': 66
    '[BH2]': 67
    '[BH3-]': 68
    '[BH]': 69
    '[B]': 70
    '[Ba]': 71
    '[Be]': 72
    '[Bi+2]': 73
    '[Bi+]': 74
    '[Bi-]': 75
    '[BiH2]': 76
    '[BiH]': 77
    '[Bi]': 78
    '[Br+2]': 79
    '[Br+3]': 80
    '[Br+]': 81
    '[Br-]': 82
    '[Br]': 83
    '[C+]': 84
    '[C-]': 85
    '[CH+]': 86
    '[CH-]': 87
    '[CH2+]': 88
    '[CH2-]': 89
    '[CH2]': 90
    '[CH3+]': 91
    '[CH]': 92
    '[C]': 93
    '[Ca]': 94
    '[Cd-2]': 95
    '[Cd]': 96
    '[Ce+3]': 97
    '[Ce]': 98
    '[Cf]': 99
    '[Cl+2]': 100
    '[Cl+3]': 101
    '[Cl+]': 102
    '[ClH+2]': 103
    '[ClH+]': 104
    '[ClH2+2]': 105
    '[ClH3+3]': 106
    '[Cm]': 107
    '[Co+2]': 108
    '[Co-2]': 109
    '[Co]': 110
    '[Cr+2]': 111
    '[Cr+6]': 112
    '[Cr+]': 113
    '[Cr-2]': 114
    '[Cr]': 115
    '[Cs+]': 116
    '[Cs]': 117
    '[Cu-]': 118
    '[Cu]': 119
    '[Dy]': 120
    '[Er]': 121
    '[Es]': 122
    '[Eu]': 123
    '[Fe+3]': 124
    '[Fe+5]': 125
    '[Fe+]': 126
    '[Fe-2]': 127
    '[Fe-4]': 128
    '[Fe]': 129
    '[Ga-]': 130
    '[GaH2]': 131
    '[GaH]': 132
    '[Ga]': 133
    '[Gd+3]': 134
    '[Gd]': 135
    '[GeH2]': 136
    '[GeH3]': 137
    '[GeH]': 138
    '[Ge]': 139
    '[HH]': 140
    '[H]': 141
    '[Hf+2]': 142
    '[Hf]': 143
    '[Hg+]': 144
    '[HgH]': 145
    '[Hg]': 146
    '[Ho]': 147
    '[I+2]': 148
    '[I+3]': 149
    '[I+]': 150
    '[I-]': 151
    '[IH+]': 152
    '[IH2+]': 153
    '[IH]': 154
    '[InH2]': 155
    '[InH]': 156
    '[In]': 157
    '[Ir+2]': 158
    '[IrH2]': 159
    '[IrH3]': 160
    '[Ir]': 161
    '[K]': 162
    '[Kr]': 163
    '[La]': 164
    '[Li]': 165
    '[Lu]': 166
    '[Md]': 167
    '[Mg+]': 168
    '[Mg]': 169
    '[Mn]': 170
    '[Mo+2]': 171
    '[Mo+]': 172
    '[Mo-2]': 173
    '[MoH2]': 174
    '[Mo]': 175
    '[N+]': 176
    '[N-]': 177
    '[NH+]': 178
    '[NH-]': 179
    '[NH2+]': 180
    '[NH3+]': 181
    '[NH]': 182
    '[N]': 183
    '[Na]': 184
    '[Nb-2]': 185
    '[Nb]': 186
    '[Nd]': 187
    '[Ni+2]': 188
    '[Ni+]': 189
    '[Ni-3]': 190
    '[Ni-]': 191
    '[NiH]': 192
    '[Ni]': 193
    '[Np]': 194
    '[O+]': 195
    '[O-]': 196
    '[OH+]': 197
    '[OH2+]': 198
    '[OH3+]': 199
    '[OH]': 200
    '[O]': 201
    '[Os+2]': 202
    '[Os+8]': 203
    '[Os-]': 204
    '[OsH]': 205
    '[Os]': 206
    '[P+]': 207
    '[P-2]': 208
    '[P-]': 209
    '[PH+]': 210
    '[PH-]': 211
    '[PH2+]': 212
    '[PH2]': 213
    '[PH3+]': 214
    '[PH]': 215
    '[P]': 216
    '[PbH2]': 217
    '[PbH3]': 218
    '[PbH]': 219
    '[Pb]': 220
    '[Pd-]': 221
    '[Pd]': 222
    '[PoH2]': 223
    '[PoH]': 224
    '[Po]': 225
    '[Pr+]': 226
    '[Pr]': 227
    '[Pt-2]': 228
    '[PtH3]': 229
    '[Pt]': 230
    '[Pu]': 231
    '[Rb]': 232
    '[Re-2]': 233
    '[ReH2]': 234
    '[ReH4]': 235
    '[Re]': 236
    '[Rh+]': 237
    '[Rh-3]': 238
    '[Rh-]': 239
    '[RhH2]': 240
    '[Rh]': 241
    '[Rn]': 242
    '[Ru+]': 243
    '[Ru-4]': 244
    '[Ru]': 245
    '[S+]': 246
    '[S-]': 247
    '[SH+]': 248
    '[SH-]': 249
    '[SH2+]': 250
    '[SH2]': 251
    '[SH]': 252
    '[S]': 253
    '[Sb+]': 254
    '[Sb-]': 255
    '[SbH2]': 256
    '[SbH3+]': 257
    '[SbH3]': 258
    '[SbH]': 259
    '[Sb]': 260
    '[Sc]': 261
    '[Se+]': 262
    '[Se-]': 263
    '[SeH2+]': 264
    '[SeH2]': 265
    '[SeH]': 266
    '[Se]': 267
    '[Si+2]': 268
    '[Si+3]': 269
    '[Si+]': 270
    '[Si-]': 271
    '[SiH+2]': 272
    '[SiH+]': 273
    '[SiH-]': 274
    '[SiH2+]': 275
    '[SiH2-]': 276
    '[SiH2]': 277
    '[SiH3-]': 278
    '[SiH3]': 279
    '[SiH]': 280
    '[Si]': 281
    '[Sm]': 282
    '[Sn+2]': 283
    '[Sn+3]': 284
    '[Sn+]': 285
    '[Sn-]': 286
    '[SnH+]': 287
    '[SnH2-]': 288
    '[SnH2]': 289
    '[SnH3-]': 290
    '[SnH3]': 291
    '[SnH]': 292
    '[Sn]': 293
    '[Sr+2]': 294
    '[Sr]': 295
    '[Ta-2]': 296
    '[Ta-]': 297
    '[Ta]': 298
    '[Tb]': 299
    '[Tc+2]': 300
    '[Tc+3]': 301
    '[Tc+4]': 302
    '[Tc+5]': 303
    '[Tc]': 304
    '[Te+]': 305
    '[TeH3]': 306
    '[TeH4]': 307
    '[TeH]': 308
    '[Te]': 309
    '[Th+2]': 310
    '[Th]': 311
    '[Ti+2]': 312
    '[Ti+3]': 313
    '[Ti+]': 314
    '[Ti]': 315
    '[TlH2]': 316
    '[TlH]': 317
    '[Tl]': 318
    '[Tm]': 319
    '[U+2]': 320
    '[U+3]': 321
    '[UH2]': 322
    '[U]': 323
    '[V+2]': 324
    '[V+4]': 325
    '[V+]': 326
    '[V]': 327
    '[W+]': 328
    '[WH]': 329
    '[W]': 330
    '[XeH]': 331
    '[Xe]': 332
    '[YH]': 333
    '[Y]': 334
    '[Yb]': 335
    '[Zn+2]': 336
    '[Zn]': 337
    '[Zr+2]': 338
    '[Zr+]': 339
    '[Zr]': 340
    '[b-]': 341
    '[bH-]': 342
    '[c+]': 343
    '[c-]': 344
    '[cH+]': 345
    '[cH-]': 346
    '[c]': 347
    '[n+]': 348
    '[n-]': 349
    '[nH+]': 350
    '[nH]': 351
    '[o+]': 352
    '[oH+]': 353
    '[p+]': 354
    '[p-]': 355
    '[pH+]': 356
    '[pH]': 357
    '[s+]': 358
    '[sH+]': 359
    '[se+]': 360
    '[se]': 361
    '[si-]': 362
    '[siH]': 363
    '[si]': 364
    '[te+]': 365
    '[te]': 366
    b: 367
    c: 368
    n: 369
    o: 370
    p: 371
    s: 372
  tokens:
  - '#'
  - '%10'
  - '%11'
  - '%12'
  - '%13'
  - '%14'
  - '%15'
  - '%16'
  - '%17'
  - '%18'
  - '%19'
  - '%20'
  - '%21'
  - '%22'
  - (
  - )
  - '*'
  - '-'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '='
  - B
  - Br
  - C
  - Cl
  - F
  - I
  - N
  - O
  - P
  - S
  - '[Ac]'
  - '[Ag]'
  - '[Al+2]'
  - '[Al+]'
  - '[Al-3]'
  - '[Al-]'
  - '[AlH+]'
  - '[AlH-]'
  - '[AlH2-]'
  - '[AlH2]'
  - '[AlH3-]'
  - '[AlH]'
  - '[Al]'
  - '[Am]'
  - '[Ar]'
  - '[As+5]'
  - '[As+]'
  - '[As-]'
  - '[AsH+]'
  - '[AsH2+]'
  - '[AsH2]'
  - '[AsH3+]'
  - '[AsH]'
  - '[As]'
  - '[At]'
  - '[Au]'
  - '[B-]'
  - '[BH-]'
  - '[BH2-]'
  - '[BH2]'
  - '[BH3-]'
  - '[BH]'
  - '[B]'
  - '[Ba]'
  - '[Be]'
  - '[Bi+2]'
  - '[Bi+]'
  - '[Bi-]'
  - '[BiH2]'
  - '[BiH]'
  - '[Bi]'
  - '[Br+2]'
  - '[Br+3]'
  - '[Br+]'
  - '[Br-]'
  - '[Br]'
  - '[C+]'
  - '[C-]'
  - '[CH+]'
  - '[CH-]'
  - '[CH2+]'
  - '[CH2-]'
  - '[CH2]'
  - '[CH3+]'
  - '[CH]'
  - '[C]'
  - '[Ca]'
  - '[Cd-2]'
  - '[Cd]'
  - '[Ce+3]'
  - '[Ce]'
  - '[Cf]'
  - '[Cl+2]'
  - '[Cl+3]'
  - '[Cl+]'
  - '[ClH+2]'
  - '[ClH+]'
  - '[ClH2+2]'
  - '[ClH3+3]'
  - '[Cm]'
  - '[Co+2]'
  - '[Co-2]'
  - '[Co]'
  - '[Cr+2]'
  - '[Cr+6]'
  - '[Cr+]'
  - '[Cr-2]'
  - '[Cr]'
  - '[Cs+]'
  - '[Cs]'
  - '[Cu-]'
  - '[Cu]'
  - '[Dy]'
  - '[Er]'
  - '[Es]'
  - '[Eu]'
  - '[Fe+3]'
  - '[Fe+5]'
  - '[Fe+]'
  - '[Fe-2]'
  - '[Fe-4]'
  - '[Fe]'
  - '[Ga-]'
  - '[GaH2]'
  - '[GaH]'
  - '[Ga]'
  - '[Gd+3]'
  - '[Gd]'
  - '[GeH2]'
  - '[GeH3]'
  - '[GeH]'
  - '[Ge]'
  - '[HH]'
  - '[H]'
  - '[Hf+2]'
  - '[Hf]'
  - '[Hg+]'
  - '[HgH]'
  - '[Hg]'
  - '[Ho]'
  - '[I+2]'
  - '[I+3]'
  - '[I+]'
  - '[I-]'
  - '[IH+]'
  - '[IH2+]'
  - '[IH]'
  - '[InH2]'
  - '[InH]'
  - '[In]'
  - '[Ir+2]'
  - '[IrH2]'
  - '[IrH3]'
  - '[Ir]'
  - '[K]'
  - '[Kr]'
  - '[La]'
  - '[Li]'
  - '[Lu]'
  - '[Md]'
  - '[Mg+]'
  - '[Mg]'
  - '[Mn]'
  - '[Mo+2]'
  - '[Mo+]'
  - '[Mo-2]'
  - '[MoH2]'
  - '[Mo]'
  - '[N+]'
  - '[N-]'
  - '[NH+]'
  - '[NH-]'
  - '[NH2+]'
  - '[NH3+]'
  - '[NH]'
  - '[N]'
  - '[Na]'
  - '[Nb-2]'
  - '[Nb]'
  - '[Nd]'
  - '[Ni+2]'
  - '[Ni+]'
  - '[Ni-3]'
  - '[Ni-]'
  - '[NiH]'
  - '[Ni]'
  - '[Np]'
  - '[O+]'
  - '[O-]'
  - '[OH+]'
  - '[OH2+]'
  - '[OH3+]'
  - '[OH]'
  - '[O]'
  - '[Os+2]'
  - '[Os+8]'
  - '[Os-]'
  - '[OsH]'
  - '[Os]'
  - '[P+]'
  - '[P-2]'
  - '[P-]'
  - '[PH+]'
  - '[PH-]'
  - '[PH2+]'
  - '[PH2]'
  - '[PH3+]'
  - '[PH]'
  - '[P]'
  - '[PbH2]'
  - '[PbH3]'
  - '[PbH]'
  - '[Pb]'
  - '[Pd-]'
  - '[Pd]'
  - '[PoH2]'
  - '[PoH]'
  - '[Po]'
  - '[Pr+]'
  - '[Pr]'
  - '[Pt-2]'
  - '[PtH3]'
  - '[Pt]'
  - '[Pu]'
  - '[Rb]'
  - '[Re-2]'
  - '[ReH2]'
  - '[ReH4]'
  - '[Re]'
  - '[Rh+]'
  - '[Rh-3]'
  - '[Rh-]'
  - '[RhH2]'
  - '[Rh]'
  - '[Rn]'
  - '[Ru+]'
  - '[Ru-4]'
  - '[Ru]'
  - '[S+]'
  - '[S-]'
  - '[SH+]'
  - '[SH-]'
  - '[SH2+]'
  - '[SH2]'
  - '[SH]'
  - '[S]'
  - '[Sb+]'
  - '[Sb-]'
  - '[SbH2]'
  - '[SbH3+]'
  - '[SbH3]'
  - '[SbH]'
  - '[Sb]'
  - '[Sc]'
  - '[Se+]'
  - '[Se-]'
  - '[SeH2+]'
  - '[SeH2]'
  - '[SeH]'
  - '[Se]'
  - '[Si+2]'
  - '[Si+3]'
  - '[Si+]'
  - '[Si-]'
  - '[SiH+2]'
  - '[SiH+]'
  - '[SiH-]'
  - '[SiH2+]'
  - '[SiH2-]'
  - '[SiH2]'
  - '[SiH3-]'
  - '[SiH3]'
  - '[SiH]'
  - '[Si]'
  - '[Sm]'
  - '[Sn+2]'
  - '[Sn+3]'
  - '[Sn+]'
  - '[Sn-]'
  - '[SnH+]'
  - '[SnH2-]'
  - '[SnH2]'
  - '[SnH3-]'
  - '[SnH3]'
  - '[SnH]'
  - '[Sn]'
  - '[Sr+2]'
  - '[Sr]'
  - '[Ta-2]'
  - '[Ta-]'
  - '[Ta]'
  - '[Tb]'
  - '[Tc+2]'
  - '[Tc+3]'
  - '[Tc+4]'
  - '[Tc+5]'
  - '[Tc]'
  - '[Te+]'
  - '[TeH3]'
  - '[TeH4]'
  - '[TeH]'
  - '[Te]'
  - '[Th+2]'
  - '[Th]'
  - '[Ti+2]'
  - '[Ti+3]'
  - '[Ti+]'
  - '[Ti]'
  - '[TlH2]'
  - '[TlH]'
  - '[Tl]'
  - '[Tm]'
  - '[U+2]'
  - '[U+3]'
  - '[UH2]'
  - '[U]'
  - '[V+2]'
  - '[V+4]'
  - '[V+]'
  - '[V]'
  - '[W+]'
  - '[WH]'
  - '[W]'
  - '[XeH]'
  - '[Xe]'
  - '[YH]'
  - '[Y]'
  - '[Yb]'
  - '[Zn+2]'
  - '[Zn]'
  - '[Zr+2]'
  - '[Zr+]'
  - '[Zr]'
  - '[b-]'
  - '[bH-]'
  - '[c+]'
  - '[c-]'
  - '[cH+]'
  - '[cH-]'
  - '[c]'
  - '[n+]'
  - '[n-]'
  - '[nH+]'
  - '[nH]'
  - '[o+]'
  - '[oH+]'
  - '[p+]'
  - '[p-]'
  - '[pH+]'
  - '[pH]'
  - '[s+]'
  - '[sH+]'
  - '[se+]'
  - '[se]'
  - '[si-]'
  - '[siH]'
  - '[si]'
  - '[te+]'
  - '[te]'
  - b
  - c
  - n
  - o
  - p
  - s
