
model_name: model_bci
save_path: null

epochs: 100

Dataset:
  shuffle: true
  x_basepath: data/BCI_KAGGLE/KaggleBCI_dataset_PROCESSED/original
  y_basepath: data/BCI_KAGGLE/KaggleBCI_dataset_PROCESSED/ICA
  x_fpath: Data_S{}.set
  y_fpath: Data_S{}_Sess.set
  sfreq: 128.0
  n_chan: 56
  subjects_train:
    - ["02"]
    - ["06"]
    - ["07"]
    - ["11"]
    - ["12"]
    - ["13"]
    - ["14"]
    - ["16"]
    - ["17"]
    - ["18"]
    - ["26"]
  subjects_val:
    - ["20"]
    - ["21"]
    - ["22"]
    - ["23"]
    - ["24"]
  ch_names: null
  tmin: 0
  tmax: 800
  window_size: 4
  stride: 2

  