name: ldmol
channels:
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - expat=2.5.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.4
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipywidgets=8.1.2
  - jedi=0.18.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - krb5=1.20.1
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libsodium=1.0.18
  - libuuid=1.41.5
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - openssl=3.0.13
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=23.3
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.43
  - python=3.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - webencodings=0.5.1
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - accelerate==0.20.3
    - aiofiles==23.2.1
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - albumentations==1.3.1
    - altair==5.1.2
    - anthropic==0.4.1
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - bitsandbytes==0.42.0
    - blobfile==2.1.1
    - certifi==2023.7.22
    - chardet==5.2.0
    - charset-normalizer==3.3.1
    - click==8.1.7
    - cmake==3.27.7
    - contextlib2==21.6.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - dataclasses-json==0.6.1
    - datasets==2.14.5
    - deepspeed==0.10.0
    - diffusers==0.27.2
    - dill==0.3.7
    - distro==1.8.0
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - exceptiongroup==1.1.3
    - fastapi==0.103.2
    - fcd==1.2.2
    - ffmpy==0.3.1
    - filelock==3.12.4
    - fonttools==4.43.1
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - ftfy==6.1.1
    - gitdb==4.0.11
    - gitpython==3.1.40
    - gradio==3.49.0
    - gradio-client==0.6.1
    - greenlet==3.0.0
    - h11==0.14.0
    - hjson==3.1.0
    - httpcore==0.18.0
    - httptools==0.6.1
    - httpx==0.25.0
    - huggingface-hub==0.22.2
    - imageio==2.31.6
    - importlib-metadata==7.1.0
    - importlib-resources==6.1.0
    - iniconfig==2.0.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonlines==4.0.0
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jsonschema==4.19.1
    - kiwisolver==1.4.5
    - langchain==0.0.316
    - langsmith==0.0.49
    - lazy-loader==0.3
    - levenshtein==0.21.1
    - lightning-utilities==0.9.0
    - lit==17.0.3
    - lxml==4.9.3
    - markdown-it-py==3.0.0
    - markdownify==0.11.6
    - marshmallow==3.20.1
    - matplotlib==3.8.0
    - mdurl==0.1.2
    - ml-collections==0.1.1
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - multiprocess==0.70.15
    - mypy-extensions==1.0.0
    - networkx==3.2
    - ninja==1.11.1.1
    - nltk==3.8.1
    - numpy==1.22.3
    - omegaconf==2.3.0
    - openai==0.28.1
    - opencv-python-headless==4.8.1.78
    - orjson==3.9.9
    - pandas==2.0.3
    - peft==0.4.0
    - pillow==10.0.1
    - plotly==5.17.0
    - pluggy==1.3.0
    - polyglot==16.7.4
    - prompt-toolkit==3.0.39
    - protobuf==3.20.1
    - psutil==5.9.5
    - pubchempy==1.0.4
    - py-cpuinfo==9.0.0
    - pyarrow==13.0.0
    - pycld2==0.41
    - pycocoevalcap==1.2
    - pycocotools==2.0.7
    - pycryptodomex==3.20.0
    - pydantic==1.10.11
    - pydub==0.25.1
    - pyedflib==0.1.37
    - pygments==2.16.1
    - pyparsing==3.1.1
    - pysmilesutils @ git+https://github.com/MolecularAI/pysmilesutils.git
    - pytest==7.4.2
    - python-docx==1.1.0
    - python-dotenv==1.0.0
    - python-levenshtein==0.21.1
    - python-multipart==0.0.6
    - pytorch-fid==0.3.0
    - pytorch-lightning==2.1.0
    - pytz==2023.3
    - qudida==0.0.4
    - rapidfuzz==3.7.0
    - ray==2.7.1
    - rdkit==2023.3.1
    - regex==2023.6.3
    - rouge-score==0.1.2
    - rwkv==0.8.16
    - safetensors==0.4.0
    - scikit-image==0.22.0
    - scikit-learn==1.3.0
    - scipy==1.11.3
    - selfies==2.1.1
    - semantic-version==2.10.0
    - sentencepiece==0.1.99
    - sentry-sdk==1.39.1
    - setproctitle==1.3.3
    - setuptools==67.8.0
    - shortuuid==1.0.11
    - smmap==5.0.1
    - sqlalchemy==2.0.22
    - starlette==0.27.0
    - sympy==1.12
    - tenacity==8.2.3
    - threadpoolctl==3.2.0
    - tifffile==2023.9.26
    - tiktoken==0.5.1
    - timm==0.9.16
    - tokenizers==0.13.3
    - toolz==0.12.0
    - torch==2.0.1
    - torch-fidelity==0.3.0
    - torchmetrics==1.2.0
    - torchvision==0.15.2
    - tqdm==4.65.0
    - transformers==4.30.1
    - triton==2.0.0
    - typing-extensions==4.8.0
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - urllib3==2.0.7
    - uvicorn==0.23.2
    - uvloop==0.19.0
    - vertexai==0.0.1
    - wandb==0.16.1
    - watchfiles==0.21.0
    - wcwidth==0.2.8
    - websockets==11.0.3
    - xformers==0.0.22
    - xxhash==3.4.1
    - yarl==1.9.2
    - zipp==3.18.1
    #- nvidia-cublas-cu11==11.10.3.66
    #- nvidia-cuda-cupti-cu11==11.7.101
    #- nvidia-cuda-nvrtc-cu11==11.7.99
    #- nvidia-cuda-runtime-cu11==11.7.99
    #- nvidia-cudnn-cu11==8.5.0.96
    #- nvidia-cufft-cu11==10.9.0.58
    #- nvidia-curand-cu11==10.2.10.91
    #- nvidia-cusolver-cu11==11.4.0.1
    #- nvidia-cusparse-cu11==11.7.4.91
    #- nvidia-nccl-cu11==2.14.3
    #- nvidia-nvtx-cu11==11.7.91