name: eeg-rt-seizure-detection
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.9.23
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - einops==0.8.1
      - filelock==3.13.1
      - fonttools==4.59.0
      - fsspec==2024.6.1
      - grpcio==1.73.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - mamba-ssm==2.2.4
      - markdown==3.8.2
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mne==1.8.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.0.0
      - platformdirs==4.3.8
      - pooch==1.8.2
      - prettytable==3.16.0
      - protobuf==6.31.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.2
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchmetrics==1.7.4
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.53.3
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - xlstm==2.0.0
      - zipp==3.23.0