
model_name: cleegn_tuh
save_path: null
epochs: 80
Hyperparameter:
    d_model: 192*2
    dim: 192   # ~6M parameter model
    num_heads: 4
    epochs: 20
    batch_size: 32
    lr: 1e-4
    depth: 3
    optim_weight_decay: 0.05
    linear_decay_end: 1e-10
    warmup_perc: 0.07
    input_dim: 1
    output_dim: 1
    use_mlp_posEnc: True
    accumulation_steps: 1
Dataset:
  shuffle: true
  x_basepath: /system/user/studentwork/gutenber/TUH_dataset_PROCESSED_new/original
  y_basepath: /system/user/studentwork/gutenber/TUH_dataset_PROCESSED_new/ICA
  x_fpath: Data_S{}.set
  y_fpath: Data_S{}_ICA.set
  use_montage: 'tuh'   #'tuh', 'random' or 'no_montage'
  sfreq: 250.0
  n_chan: null
  normalize: False
  subjects_train:
    - ["001"]
    - ["003"]
    - ["004"]
    - ["005"]
    - ["006"]
    - ["007"]
    - ["008"]
    - ["009"]
    - ["012"]
    - ["013"]
    - ["014"]
    - ["015"]
    - ["020"]
    - ["021"]
    - ["022"]
    - ["023"]
    - ["024"]
    - ["025"]
    - ["026"]
    - ["027"]
    - ["028"]
    - ["029"]
    - ["030"]
    - ["031"]
    - ["033"]
    - ["034"]
    - ["037"]
    - ["038"]
    - ["041"]
    - ["042"]
    - ["043"]
    - ["044"]
    - ["045"]
    - ["046"]
    - ["047"]
    - ["048"]
    - ["050"]
    - ["051"]
  subjects_val:
    - ["010"]
    - ["011"]
    - ["060"]
    - ["066"]
    - ["140"]
    - ["131"]
    - ["197"]
  subjects_test:
    - ["016"]
    #- ["018"]
    #- ["019"]
    #- ["076"]
    #- ["165"]
  ch_names: null
  tmin: 200
  tmax: max
  window_size: 1
  stride: 1

  